# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('slug', models.CharField(max_length=255, verbose_name='URL')),
                ('type', models.CharField(max_length=255, verbose_name='类型')),
                ('args', models.TextField(verbose_name='参数')),
                ('retu', models.CharField(max_length=255, verbose_name='返回定义')),
                ('authority', models.CharField(max_length=255, verbose_name='认证')),
            ],
        ),
        migrations.CreateModel(
            name='Logic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
                ('Q', models.TextField(verbose_name='IF')),
                ('A', models.TextField(verbose_name='THEN')),
                ('T', models.IntegerField(verbose_name='周期')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('baseurl', models.CharField(max_length=255, verbose_name='基础URL')),
            ],
        ),
        migrations.AddField(
            model_name='api',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IFTHEN_db.Provider', verbose_name='提供者'),
        ),
    ]
